concurrency:
  cancel-in-progress: true

  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Change to ${{ matrix.directory }}
      run: cd ${{ matrix.directory }} 

    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json        

    - name: Install dependencies
      run: bun install

    - name: Run biome
      run: bun biome ci

    strategy:
      fail-fast: true

      matrix:
        directory:
        - .

name: CI

on:
  push:
    branches:
    - main

  pull_request:
